### ISSUE TITLE
How to specify a different port?

### ISSUE THREAD

**Issue by indera** [Appliscale/xprof#118]
I want to run two different apps from the same codebase and here is what I get when I try:

Could not start application xprof: :xprof_app.start(:normal, []) returned an error: :eaddrinuse

**Comment by gomoripeti** [comment]
Hi Andrei

Would you like to run two separate instances of `xprof` within the same Erlang VM or do you have another application listening on port 7890?

It is only possible to run one instance of `xprof` in the same VM because of the limitations of the underlying tracing framework.

You can set the `:port` application env of `:xprof` application to something different than default 7890. (For example you can put the following line in your `config/config.exs`:
```elixir
config :xprof, port: 7891
```

Let us know if this helps.

**Comment by indera** [comment]
Thank you @gomoripeti - I was trying to run two VM instances
