### ISSUE TITLE
UI Bugs - Auto-complete 

### ISSUE THREAD

**Issue by afronski** [Appliscale/xprof#19]
When you type almost full name, but without e.g. _arity_ and you hit _ENTER_ - it does not select first one out of the box. 

The same if you choose one with arrows and then hit _ENTER_ - it does not search that one out of the box, you need second _ENTER_ hit for those.

**Comment by gomoripeti** [comment]
documenting current behaviour:
- by default no item is selected/highlighted in the dropdown list (even if there is only one element - this is inconvenient)
- TAB: if there is a selected item copy it (aka auto-complete) into the textbox
- ENTER: if textbox input matches some mfa regexp then add graph
  otherwise works as TAB

without specifying full desired behaviour:
- mfa regexp will have to be removed from front-end to allow more flexible parsing (match-spec funs, Elixir etc) therefore ENTER can do only one thing - it could be to always send the textbox content (no matter what it is) so the back-end tries to start tracing
- TAB could auto-complete to the longest common prefix of all items in the dropdown list eg.
if textbox has "lists:ap" then "lists:append/"
