### ISSUE TITLE
New frontend

### ISSUE THREAD

**Issue by MarcinKasprowicz** [Appliscale/xprof#98]
I will put here my updates and thought regarding work on the new frontend.

**Comment by MarcinKasprowicz** [comment]
I started to preparing development environment - https://github.com/MarcinKasprowicz/xprof/tree/new-ui/new-priv (branch new-ui). I'm trying to document how much it is possible.

**Comment by gomoripeti** [comment]
the base of the new UI is now merged into `release_2.0` (still in the separate `new-priv` dir) however there are some existing features not yet ported:
[ ] Pause tracing should stop all polling (except polling trace status)
[ ] List called functions
[ ] Order captured calls by any column
[ ] Each graph should be grouped together with its captured calls table (right now all these tables are below all graphs)
[ ] When function is stopped being monitored, related data-points should be deleted from state (otherwise browser will run out of memory after a while)

**Comment by MarcinKasprowicz** [comment]
New frontend has been merged into `release_2.0`
